# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Recipes' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'

  # Pods for Recipes

  target 'RecipesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecipesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
